version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: airflow_webserver

    command: >
      bash -c "
      pip install dbt-core dbt-snowflake &&
      airflow webserver
      "

    ports:
      - "8080:8080"

    environment:
      PYTHONPATH: /opt/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    depends_on:
      - postgres

    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./config:/opt/airflow/config
      - ./inbox:/opt/airflow/inbox
      - ./archive:/opt/airflow/archive
      - ./dbt:/opt/airflow/dbt

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: airflow_scheduler

    command: >
      bash -c "
      pip install dbt-core dbt-snowflake &&
      airflow scheduler
      "

    environment:
      PYTHONPATH: /opt/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

    depends_on:
      - postgres

    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./config:/opt/airflow/config
      - ./inbox:/opt/airflow/inbox
      - ./archive:/opt/airflow/archive
      - ./dbt:/opt/airflow/dbt

volumes:
  postgres_data: