sales_etl:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: GTFKWVR-TDC55215
      user: yaminpal
      password: Chimbita@1991$
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: SALES_DB
      schema: RAW
      threads: 4